export const DEFAULT_BRAND_ID = 'brand_default';

export const SOURCE_TYPES = ['官网 URL', 'PDF 手册', 'PPT 路演', 'FAQ 文档', '短视频字幕', '招商政策'];

export const FACT_FIELD_META = [
  { key: 'oneLiner', title: '一句话定位' },
  { key: 'industry', title: '行业归类' },
  { key: 'storeModels', title: '门店模型' },
  { key: 'targetPersona', title: '目标加盟商画像' },
  { key: 'coreSellingPoints', title: '核心卖点' },
  { key: 'investmentThreshold', title: '投资门槛' },
  { key: 'enablementPoints', title: '总部赋能点' },
  { key: 'riskPoints', title: '风险疑虑点' },
];

export const DEFAULT_BRAND = {
  id: DEFAULT_BRAND_ID,
  name: '樊文花美业集团',
  websiteUrl: 'https://brand.example.com/franchise',
  benchmarkCompany: '樊文花',
  oneLiner: '面部护理专家，全国连锁加盟品牌',
  industry: '美容美业 / 连锁加盟 / 标准店模型',
  storeModels: '标准店、旗舰店、社区店三套店型与不同投资门槛',
  targetPersona: '有美业/零售运营经验、预算 50-100 万、看重供应链与培训体系',
  coreSellingPoints: '品牌认知、供应链效率、培训赋能、标准化运营、数字化督导',
  investmentThreshold: '标准店 50-80 万，旗舰店 100 万以上，需结合城市级别和商圈测算',
  enablementPoints: '选址评估、装修设计、培训体系、开业策划、供应链支持、运营复盘',
  riskPoints: '回本周期、区域保护、加盟政策、培训落地、供应链配送、合同条款',
  missingContext: ['重点城市单店模型', '区域保护边界', 'Q2 政策细则', '竞品对比证据'],
  sourceSummary: ['官网招商页', '加盟手册', 'FAQ', '标杆案例', '政策文档'],
};

export const SKILL_GROUP_ORDER = ['按招商环节', '按行业', '按企业'];

export const BENCHMARK_SKILLS = [
  {
    id: 'skill_stage_lead_capture',
    group: '按招商环节',
    name: '线索获取对标 Skill',
    benchmark: '樊文花招商模式研究及通用招商策略',
    environments: ['prod', 'gray'],
    items: ['广告获客适配', '招商会线索建档', '转介绍线索去重'],
    connectorRequirements: ['企业微信', '活动系统', 'CRM'],
    version: 'v2.2',
    status: '已启用',
    tags: ['线索', '获客'],
  },
  {
    id: 'skill_stage_visit_sign',
    group: '按招商环节',
    name: '考察 / 签约 Skill',
    benchmark: '樊文花招商模式研究及通用招商策略',
    environments: ['prod', 'staging'],
    items: ['总部考察邀约', '样板店参观编排', '报价审批联动', '催签策略'],
    connectorRequirements: ['审批中心', '合同系统', '日程中心'],
    version: 'v2.4',
    status: '推荐安装',
    tags: ['考察', '签约'],
  },
  {
    id: 'skill_stage_silent_wakeup',
    group: '按招商环节',
    name: '沉默激活 Skill',
    benchmark: '樊文花店铺运营拆解及美业连锁通用运营体系',
    environments: ['gray', 'dev'],
    items: ['标杆案例唤醒', '区域 ROI 重构', '总部赋能证据包'],
    connectorRequirements: ['知识库', '素材中心'],
    version: 'v1.8',
    status: '灰度中',
    tags: ['沉默激活', '唤醒'],
  },
  {
    id: 'skill_industry_beauty',
    group: '按行业',
    name: '美容美业加盟',
    benchmark: '樊文花店铺运营拆解及美业连锁通用运营体系',
    environments: ['prod'],
    items: ['品牌定位话术', '供应链能力说明', '培训体系介绍', '门店模型测算'],
    connectorRequirements: ['知识库', '审批中心'],
    version: 'v3.0',
    status: '已启用',
    tags: ['美容美业', '加盟'],
  },
  {
    id: 'skill_industry_multi_store',
    group: '按行业',
    name: '多店经营加盟',
    benchmark: '行业通用模板',
    environments: ['staging'],
    items: ['多店经营画像识别', '区域保护边界说明', '城市级 ROI 对比'],
    connectorRequirements: ['CRM', '地图服务', '知识库'],
    version: 'v1.5',
    status: '推荐安装',
    tags: ['多店经营', '区域'],
  },
  {
    id: 'skill_company_fwh',
    group: '按企业',
    name: '樊文花',
    benchmark: '樊文花双文档',
    environments: ['prod', 'staging', 'gray'],
    items: ['品牌故事', '加盟政策', '培训赋能', '单店模型', '转介绍激励'],
    connectorRequirements: ['知识库', '素材中心', '审批中心', 'CRM'],
    version: 'v3.2',
    status: '标杆模板',
    tags: ['樊文花', '标杆'],
  },
  {
    id: 'skill_company_custom_hq',
    group: '按企业',
    name: '品牌总部自定义',
    benchmark: '企业自建',
    environments: ['dev'],
    items: ['招商话术', '报价规则', '区域保护边界', '合同前置问答'],
    connectorRequirements: ['品牌建模', '知识库'],
    version: 'v0.9',
    status: '开发中',
    tags: ['总部自定义', '规则'],
  },
];
