// AI 招商 Growth OS — B2B 招商加盟 Mock 数据
// 线索是代理商/加盟商负责人（B端客户）

import { mockLeads as generatedLeads, mockMessages as generatedMessages, mockPersona as generatedPersona } from './generatedMockData';

export const mockLeads = generatedLeads;
export const mockMessages = generatedMessages;


export const mockApprovals = [
  {
    id: 'appr_1',
    type: 'policy',
    title: '华南区域加盟政策调整审批',
    description: '将华南区标准店加盟费从35万调整为30万，有效期至2026年Q2末',
    sourceAgent: 'Playbook Planner Agent',
    sourceSkillVersion: 'franchise-policy-v2.1',
    riskLevel: 'medium',
    impact: '预计影响华南区12个在谈线索的报价',
    recommendation: '建议通过。当前华南区签约率偏低，调价有望提升15%转化率',
    alternatives: ['仅降低首付比例', '增加赠送服务包代替降价'],
    status: 'pending',
    createdAt: '2026-04-19T09:00:00Z',
    expiresAt: '2026-04-21T09:00:00Z',
    runId: 'run_1',
    objectType: 'playbook',
    objectName: '华南区 Q2 招商方案',
  },
  {
    id: 'appr_2',
    type: 'budget',
    title: '上海招商会追加预算审批',
    description: '追加5万元用于上海招商会后续线索跟进物料制作',
    sourceAgent: 'Asset Generation Agent',
    sourceSkillVersion: 'event-followup-v1.3',
    riskLevel: 'low',
    impact: '预算从15万增加至20万',
    recommendation: '建议通过。招商会获取32条有效线索，物料投入ROI预估3.2x',
    alternatives: ['使用现有通用物料', '缩减物料范围至核心5件'],
    status: 'pending',
    createdAt: '2026-04-18T15:00:00Z',
    expiresAt: '2026-04-22T15:00:00Z',
    runId: 'run_2',
    objectType: 'event',
    objectName: '上海招商会会后跟进',
  },
  {
    id: 'appr_3',
    type: 'outreach',
    title: '高频触达审批 - 李美琴',
    description: 'AI建议在48小时内对李美琴发起3次跟进触达（企微+电话+邮件）',
    sourceAgent: 'Invite Agent',
    sourceSkillVersion: 'lead-nurture-v1.0',
    riskLevel: 'high',
    impact: '高频触达可能造成反感，但该线索紧迫度高',
    recommendation: '建议通过但调整为2次（企微+电话），邮件改为3天后',
    alternatives: ['仅企微跟进', '等待客户主动回复'],
    status: 'pending',
    createdAt: '2026-04-20T08:00:00Z',
    expiresAt: '2026-04-20T20:00:00Z',
    runId: 'run_3',
    objectType: 'lead',
    objectName: '李美琴',
  },
  {
    id: 'appr_4',
    type: 'policy',
    title: '杭州区域独家代理权审批',
    description: '刘婉清申请杭州滨江区独家代理权，排他半径3公里',
    sourceAgent: 'Orchestrator Agent',
    sourceSkillVersion: 'franchise-policy-v2.1',
    riskLevel: 'medium',
    impact: '将限制滨江区3公里内新加盟商准入',
    recommendation: '建议通过。该区域市场容量支撑1家标准店，独家权有利于加盟商信心',
    alternatives: ['缩小排他半径至1.5公里', '不授予独家但给予优先权'],
    status: 'approved',
    createdAt: '2026-04-16T10:00:00Z',
    expiresAt: '2026-04-19T10:00:00Z',
    runId: 'run_4',
    objectType: 'lead',
    objectName: '刘婉清',
    decidedAt: '2026-04-16T13:20:00Z',
  },
  {
    id: 'appr_5',
    type: 'skill_activation',
    title: '樊文花招商模式 Skill 激活审批',
    description: '将「樊文花招商模式 v2.2」设为华南大区默认执行 Skill，并替换现有话术模版',
    sourceAgent: 'Brand Modeling Agent',
    sourceSkillVersion: 'benchmark-franchise-v2.2',
    riskLevel: 'medium',
    impact: '会影响华南区 38 条线索的后续推荐话术与 Playbook 模板',
    recommendation: '建议通过。新版本补齐了总部考察与催签阶段话术，且回归结果优于当前版本',
    alternatives: ['仅灰度到华南团队', '保留旧版评分逻辑，仅替换话术模板'],
    status: 'superseded',
    createdAt: '2026-04-17T07:40:00Z',
    expiresAt: '2026-04-20T08:00:00Z',
    runId: 'run_1',
    objectType: 'skill',
    objectName: '樊文花招商模式',
    supersededBy: 'appr_6',
    decidedAt: '2026-04-19T10:15:00Z',
  },
  {
    id: 'appr_6',
    type: 'referral',
    title: '老加盟商转介绍激励发布审批',
    description: '面向华东和华南已签约加盟商发布 Q2 转介绍激励，推荐新加盟商签约后返现 2%',
    sourceAgent: 'Referral Design Agent',
    sourceSkillVersion: 'referral-growth-v1.0',
    riskLevel: 'medium',
    impact: '预计覆盖 62 家存量加盟商，需同步结算与反作弊规则',
    recommendation: '建议通过，但要求先启用签到校验和重复推荐去重规则',
    alternatives: ['仅对高活跃加盟商开放', '返现改为物料券与培训券'],
    status: 'pending',
    createdAt: '2026-04-20T03:30:00Z',
    expiresAt: '2026-04-23T03:30:00Z',
    runId: 'run_2',
    objectType: 'referral_program',
    objectName: 'Q2 转介绍激励',
  },
  {
    id: 'appr_7',
    type: 'external_delivery',
    title: '加盟手册与 ROI 测算表外发审批',
    description: '向成都线索张国栋外发最新版加盟手册、ROI 测算表与同城标杆案例摘要',
    sourceAgent: 'Asset Generation Agent',
    sourceSkillVersion: 'asset-bundle-v1.4',
    riskLevel: 'low',
    impact: '涉及 3 份外发资料，包含区域经营数据与总部赋能细节',
    recommendation: '建议通过。该线索投资能力高，资料外发能提升总部考察转化率',
    alternatives: ['仅发送手册摘要', '先发送公开版案例，ROI 表待视频沟通后再外发'],
    status: 'pending',
    createdAt: '2026-04-20T05:10:00Z',
    expiresAt: '2026-04-21T05:10:00Z',
    runId: 'run_2',
    objectType: 'asset_bundle',
    objectName: '张国栋资料外发包',
  },
];

export const mockAgentRuns = [
  {
    id: 'run_1',
    agentType: 'Playbook Planner',
    status: 'paused_for_approval',
    startedAt: '2026-04-19T08:55:00Z',
    currentStep: '方案审批中',
    steps: ['分析市场数据', '生成3套方案', '对比预测', '方案审批中'],
    approvalId: 'appr_1',
    triggerSource: 'autonomous',
    stage: 'visit_invite',
  },
  {
    id: 'run_2',
    agentType: 'Asset Generation',
    status: 'paused_for_approval',
    startedAt: '2026-04-18T14:50:00Z',
    currentStep: '预算审批中',
    steps: ['分析线索画像', '生成物料方案', '预算审批中'],
    approvalId: 'appr_2',
    triggerSource: 'autonomous',
    stage: 'sign_push',
  },
  {
    id: 'run_3',
    agentType: 'Lead Scoring',
    status: 'completed',
    startedAt: '2026-04-20T06:00:00Z',
    currentStep: '完成',
    steps: ['扫描全部线索', '更新评分', '生成建议', '完成'],
    approvalId: null,
  },
  {
    id: 'run_4',
    agentType: '总部考察邀约 Agent',
    status: 'running',
    startedAt: '2026-04-20T10:10:00Z',
    currentStep: '同步考察档期',
    steps: ['识别高意向线索', '同步考察档期', '生成邀约话术', '等待确认'],
    approvalId: null,
    triggerSource: 'manual_command',
    stage: 'visit_invite',
  },
  {
    id: 'run_5',
    agentType: '沉默激活 Agent',
    status: 'running',
    startedAt: '2026-04-20T07:40:00Z',
    currentStep: '发送标杆案例',
    steps: ['识别沉默线索', '生成唤醒理由', '发送标杆案例', '等待反馈'],
    approvalId: null,
    triggerSource: 'journey',
    stage: 'silent_wake',
  },
];

export const mockEvents = [
  {
    id: 'evt_1',
    title: '广州天河区招商说明会',
    city: '广州',
    type: 'seminar',
    date: '2026-04-25',
    time: '14:00-17:00',
    venue: '广州天河希尔顿酒店3F',
    capacity: 50,
    registered: 38,
    confirmed: 28,
    attended: 0,
    status: 'upcoming',
    inviteWave: 2,
    relatedLeads: ['lead_1'],
  },
  {
    id: 'evt_2',
    title: '上海品牌考察日',
    city: '上海',
    type: 'site_visit',
    date: '2026-04-22',
    time: '10:00-16:00',
    venue: '上海分公司展厅+标杆门店',
    capacity: 10,
    registered: 8,
    confirmed: 6,
    attended: 0,
    status: 'upcoming',
    inviteWave: 1,
    relatedLeads: ['lead_2'],
  },
];

export const mockPlaybooks = [
  {
    id: 'pb_1',
    title: '华南区Q2招商方案 - 进取型',
    status: 'pending_approval',
    strategy: '降低加盟门槛 + 加大招商会频次 + 标杆店参观',
    description: '通过降低首批加盟费门槛吸引更多意向代理商，同时加大线下招商会频次和标杆门店参观覆盖率，快速扩大签约漏斗。',
    targetRegion: '华南',
    predictedSignRate: '18%',
    predictedROI: '2.8x',
    targetLeads: 45,
    budget: '50万',
    skillVersion: 'franchise-policy-v2.1',
    relatedApprovals: ['appr_1'],
    createdAt: '2026-04-18T10:00:00Z',
    assets: [
      { type: 'handbook', name: '华南区加盟手册 Q2版', status: 'ready' },
      { type: 'poster', name: '招商会主视觉海报', status: 'ready' },
      { type: 'xiaohongshu', name: '小红书种草文案 x5', status: 'generating' },
      { type: 'video_script', name: '品牌故事短视频脚本', status: 'ready' },
      { type: 'faq', name: '加盟常见问题 FAQ', status: 'ready' },
    ],
    milestones: [
      { name: '方案生成', status: 'done', date: '2026-04-18' },
      { name: '素材制作', status: 'in_progress', date: '2026-04-20' },
      { name: '审批发布', status: 'pending', date: '2026-04-22' },
      { name: '启动执行', status: 'pending', date: '2026-04-23' },
    ],
  },
  {
    id: 'pb_2',
    title: '华南区Q2招商方案 - 稳健型',
    status: 'draft',
    strategy: '维持现有政策 + 精准线索培育 + 转介绍激励',
    description: '保持现有加盟政策不变，聚焦高意向线索的精准培育和老加盟商转介绍裂变，以更低成本获取高质量签约。',
    targetRegion: '华南',
    predictedSignRate: '12%',
    predictedROI: '3.5x',
    targetLeads: 30,
    budget: '30万',
    skillVersion: 'franchise-policy-v2.1',
    relatedApprovals: [],
    createdAt: '2026-04-18T10:00:00Z',
    assets: [
      { type: 'handbook', name: '标准加盟手册', status: 'ready' },
      { type: 'case_study', name: '华南标杆加盟商案例集', status: 'ready' },
      { type: 'referral_kit', name: '转介绍激励物料包', status: 'pending' },
    ],
    milestones: [
      { name: '方案生成', status: 'done', date: '2026-04-18' },
      { name: '素材制作', status: 'pending', date: '2026-04-22' },
      { name: '审批发布', status: 'pending', date: '2026-04-24' },
      { name: '启动执行', status: 'pending', date: '2026-04-25' },
    ],
  },
  {
    id: 'pb_3',
    title: '华南区Q2招商方案 - 保守型',
    status: 'draft',
    strategy: '仅维护现有Pipeline + 控制预算 + 线上为主',
    description: '不做额外市场投放，仅维护现有线索池，以线上内容运营和自动化跟进为主，最大化投入产出比。',
    targetRegion: '华南',
    predictedSignRate: '8%',
    predictedROI: '4.2x',
    targetLeads: 20,
    budget: '15万',
    skillVersion: 'franchise-policy-v2.1',
    relatedApprovals: [],
    createdAt: '2026-04-18T10:00:00Z',
    assets: [
      { type: 'xiaohongshu', name: '线上种草内容 x10', status: 'ready' },
      { type: 'faq', name: '线上咨询 FAQ', status: 'ready' },
    ],
    milestones: [
      { name: '方案生成', status: 'done', date: '2026-04-18' },
      { name: '内容准备', status: 'pending', date: '2026-04-24' },
      { name: '启动执行', status: 'pending', date: '2026-04-25' },
    ],
  },
];

export const mockAiCommands = [
  {
    id: 'cmd_1',
    input: '筛出华南区意向最高的加盟商，安排总部考察和签约面谈',
    intent: 'lead_filter_and_invite',
    status: 'completed',
    createdAt: '2026-04-20T09:30:00Z',
    resultSummary: '筛选出 3 位高意向加盟商：王志远(4.6)、李美琴(4.8)、刘婉清(5.0)。已为王志远和李美琴创建总部考察邀约序列。',
    linkedObjects: [
      { type: 'lead', id: 'lead_1', name: '王志远' },
      { type: 'lead', id: 'lead_2', name: '李美琴' },
    ],
    runId: 'run_3',
    approvalId: null,
  },
  {
    id: 'cmd_2',
    input: '把 24 小时内要过期的审批汇总给我',
    intent: 'approval_query',
    status: 'completed',
    createdAt: '2026-04-20T08:15:00Z',
    resultSummary: '找到 2 项即将过期的审批：高频触达审批-李美琴（12小时内到期）、华南区政策调整审批（24小时内到期）。',
    linkedObjects: [
      { type: 'approval', id: 'appr_3', name: '高频触达审批-李美琴' },
      { type: 'approval', id: 'appr_1', name: '华南区政策调整审批' },
    ],
    runId: null,
    approvalId: null,
  },
  {
    id: 'cmd_3',
    input: '生成华南区Q2的3套招商方案',
    intent: 'playbook_generate',
    status: 'completed',
    createdAt: '2026-04-18T10:00:00Z',
    resultSummary: '已生成 3 套华南区 Q2 招商方案：进取型(签约率18%/ROI 2.8x)、稳健型(12%/3.5x)、保守型(8%/4.2x)。进取型方案已提交审批。',
    linkedObjects: [
      { type: 'playbook', id: 'pb_1', name: '进取型方案' },
      { type: 'playbook', id: 'pb_2', name: '稳健型方案' },
      { type: 'playbook', id: 'pb_3', name: '保守型方案' },
    ],
    runId: 'run_1',
    approvalId: 'appr_1',
  },
  {
    id: 'cmd_4',
    input: '总结本周招商漏斗异常，并给出下一轮优化建议',
    intent: 'analytics_report',
    status: 'completed',
    createdAt: '2026-04-19T17:00:00Z',
    resultSummary: '本周异常：华南区"已考察→谈判"转化率下降 8%，主因：2 条高意向线索沉默超 7 天。建议：对张国栋发送同城案例数据唤醒，对李美琴加速培训方案沟通。',
    linkedObjects: [
      { type: 'lead', id: 'lead_3', name: '张国栋' },
      { type: 'lead', id: 'lead_2', name: '李美琴' },
    ],
    runId: null,
    approvalId: null,
  },
  {
    id: 'cmd_5',
    input: '向张国栋外发加盟手册和ROI测算表',
    intent: 'asset_delivery',
    status: 'pending_approval',
    createdAt: '2026-04-20T05:10:00Z',
    resultSummary: '已生成外发资料包（加盟手册+ROI测算表+同城标杆案例摘要），需审批后发送。',
    linkedObjects: [
      { type: 'lead', id: 'lead_3', name: '张国栋' },
      { type: 'approval', id: 'appr_7', name: '外发审批' },
    ],
    runId: 'run_2',
    approvalId: 'appr_7',
  },
];

export const mockTimelines = {
  'lead_1': [
    { id: 'tl_1_1', type: 'wecom', content: '加为企微好友', timestamp: '2026-04-15T10:00:00Z', source: 'human', detail: '招商顾问-华南 手动添加' },
    { id: 'tl_1_2', type: 'wecom', content: '发送品牌介绍资料', timestamp: '2026-04-15T10:30:00Z', source: 'ai', agent: 'Asset Generation Agent', detail: '发送品牌手册PDF+门店实拍视频' },
    { id: 'tl_1_3', type: 'phone', content: '首次电话沟通 12分钟', timestamp: '2026-04-16T14:00:00Z', source: 'human', detail: '了解投资预算、经营经验、选址偏好' },
    { id: 'tl_1_4', type: 'event', content: '报名广州招商说明会', timestamp: '2026-04-17T09:00:00Z', source: 'ai', agent: 'Invite Agent', detail: '4月25日广州天河希尔顿' },
    { id: 'tl_1_5', type: 'site_visit', content: '总部考察（已完成）', timestamp: '2026-04-18T10:00:00Z', source: 'human', detail: '参观总部展厅+标杆门店，对供应链体系非常认可' },
    { id: 'tl_1_6', type: 'ai_scoring', content: 'AI 评分更新 → 4.6', timestamp: '2026-04-18T18:00:00Z', source: 'ai', agent: 'Lead Scoring Agent', detail: '考察后意向度+0.8，综合评分4.6' },
    { id: 'tl_1_7', type: 'wecom', content: '咨询供应链配送周期', timestamp: '2026-04-19T14:30:00Z', source: 'customer', detail: '加盟后供应链配送周期是多少？能否保证48小时到货？' },
    { id: 'tl_1_8', type: 'ai_action', content: 'AI 推荐下一步：安排签约面谈', timestamp: '2026-04-19T15:00:00Z', source: 'ai', agent: 'Orchestrator Agent', detail: '基于高意向评分和已考察状态，建议48h内安排签约面谈' },
  ],
  'lead_2': [
    { id: 'tl_2_1', type: 'event', content: '参加上海招商会', timestamp: '2026-04-12T14:00:00Z', source: 'human', detail: '在招商会上表现极高兴趣，主动提问3次' },
    { id: 'tl_2_2', type: 'form', content: '提交加盟意向书', timestamp: '2026-04-12T17:00:00Z', source: 'customer', detail: '招商会现场提交意向书' },
    { id: 'tl_2_3', type: 'ai_scoring', content: 'AI 评分更新 → 4.8', timestamp: '2026-04-12T18:00:00Z', source: 'ai', agent: 'Lead Scoring Agent', detail: '招商会参与度高+意向书提交，评分4.8' },
    { id: 'tl_2_4', type: 'wecom', content: '加为企微好友', timestamp: '2026-04-13T09:00:00Z', source: 'ai', agent: 'Invite Agent', detail: '自动发起好友申请' },
    { id: 'tl_2_5', type: 'wecom', content: 'AI回复培训体系详情', timestamp: '2026-04-18T16:12:00Z', source: 'ai', agent: 'Orchestrator Agent', detail: '发送4阶段培训体系说明' },
    { id: 'tl_2_6', type: 'approval', content: '触发高频触达审批', timestamp: '2026-04-20T08:00:00Z', source: 'ai', agent: 'Invite Agent', detail: '48h内3次跟进触达需审批', approvalId: 'appr_3' },
  ],
  'lead_3': [
    { id: 'tl_3_1', type: 'referral', content: '转介绍来源登记', timestamp: '2026-04-05T14:00:00Z', source: 'system', detail: '由已签约加盟商"刘婉清"推荐' },
    { id: 'tl_3_2', type: 'phone', content: '首次电话沟通 8分钟', timestamp: '2026-04-07T09:15:00Z', source: 'human', detail: '了解基本情况，投资实力强但紧迫度低' },
    { id: 'tl_3_3', type: 'ai_scoring', content: 'AI 评分更新 → 3.2', timestamp: '2026-04-07T10:00:00Z', source: 'ai', agent: 'Lead Scoring Agent', detail: '投资能力高但紧迫度低，综合3.2' },
    { id: 'tl_3_4', type: 'ai_action', content: 'AI 建议：发送成功案例唤醒', timestamp: '2026-04-19T09:00:00Z', source: 'ai', agent: 'Orchestrator Agent', detail: '沉默12天，建议发送同城加盟商经营数据' },
  ],
};

export const mockFranchiseDocs = [
  { id: 'doc_1', name: '品牌加盟手册 2026版', type: 'handbook', format: 'PDF', size: '12.5MB', status: 'published', updatedAt: '2026-04-15T10:00:00Z', description: '包含品牌介绍、加盟模式、投资分析、门店运营指南' },
  { id: 'doc_2', name: 'ROI 投资回报测算表', type: 'roi_model', format: 'Excel', size: '2.3MB', status: 'published', updatedAt: '2026-04-10T08:00:00Z', description: '标准店/旗舰店/社区店三种模式的投资回报测算' },
  { id: 'doc_3', name: '加盟常见问题 FAQ', type: 'faq', format: 'PDF', size: '1.8MB', status: 'published', updatedAt: '2026-04-18T14:00:00Z', description: '50+ 常见问题与标准回答，含加盟费、选址、培训、供应链等' },
  { id: 'doc_4', name: '华南区标杆加盟商案例集', type: 'case_study', format: 'PDF', size: '8.7MB', status: 'published', updatedAt: '2026-04-12T16:00:00Z', description: '广州、佛山、东莞 6 家标杆店经营数据与成功经验' },
  { id: 'doc_5', name: 'Q2 加盟政策说明', type: 'policy', format: 'PDF', size: '3.1MB', status: 'draft', updatedAt: '2026-04-19T09:00:00Z', description: '2026 Q2 加盟费调整、补贴政策、区域保护规则' },
  { id: 'doc_6', name: '门店选址评估指南', type: 'guide', format: 'PDF', size: '5.4MB', status: 'published', updatedAt: '2026-03-20T10:00:00Z', description: '选址标准、商圈分析模型、竞品距离要求、人流量评估' },
  { id: 'doc_7', name: '培训体系大纲', type: 'training', format: 'PDF', size: '4.2MB', status: 'published', updatedAt: '2026-04-01T08:00:00Z', description: '4阶段培训体系：总部集训→门店实训→开业辅导→持续赋能' },
  { id: 'doc_8', name: '供应链配送说明', type: 'supply_chain', format: 'PDF', size: '2.8MB', status: 'published', updatedAt: '2026-03-15T10:00:00Z', description: '全国仓储布局、配送时效、订货流程、物料清单' },
];

export const mockSkills = [
  { id: 'sk_1', name: '樊文花招商模式', version: 'v2.1', status: 'active', type: 'benchmark' },
  { id: 'sk_2', name: '标准邀约序列', version: 'v1.3', status: 'active', type: 'execution' },
  { id: 'sk_3', name: '加盟商评分模型', version: 'v1.0', status: 'active', type: 'scoring' },
];

export const mockReport = {
  reportDate: '2026-04-20',
  totalLeads: 156,
  newLeads: 8,
  highIntentLeads: 23,
  totalMessages: 89,
  sentMessages: 52,
  aiReplies: 45,
  avgResponseTime: 35,
  signingPipeline: 12,
  signedThisMonth: 3,
  conversionRate: '14.2%',
  pendingApprovals: 3,
  activeAgentRuns: 2,
  highFreqKeywords: ['加盟费', '选址', '培训', '供应链', '投资回报', '政策'],
  keyLeads: [
    { name: '王志远', reason: '高意向，已考察，待促签', action: '安排签约面谈' },
    { name: '李美琴', reason: '极高意向，谈判中，48h内需跟进', action: '发送培训方案' },
    { name: '张国栋', reason: '高净值，沉默12天，需唤醒', action: '发送成功案例' },
  ],
  funnelData: [
    { name: '线索池', value: 156 },
    { name: '已建档', value: 89 },
    { name: '已考察', value: 45 },
    { name: '谈判中', value: 23 },
    { name: '已签约', value: 12 },
  ],
  trendData: [
    { time: '周一', messages: 65, aiReplies: 42 },
    { time: '周二', messages: 78, aiReplies: 55 },
    { time: '周三', messages: 92, aiReplies: 68 },
    { time: '周四', messages: 85, aiReplies: 60 },
    { time: '周五', messages: 89, aiReplies: 45 },
  ],
  pendingTagApprovals: 2,
  pendingTaskApprovals: 3,
  aiSummary: '本周招商进展良好。华南区王志远和李美琴为最高优先级线索，建议48小时内安排签约面谈和品牌考察。成都张国栋沉默12天，建议发送同类城市加盟商经营数据唤醒。本月已签约3家，Pipeline中12家，预计Q2可达目标。',
  aiSuggestions: [
    { title: '紧急跟进李美琴', desc: '极高意向线索，招商会后48h黄金窗口', link: '查看线索' },
    { title: '审批华南区政策调整', desc: '3项待审批，含1项即将过期', link: '去审批' },
    { title: '准备广州招商说明会', desc: '4月25日，38人已报名，需确认场地', link: '查看活动' },
  ],
};

export const mockPersona = generatedPersona;
