export const currentUser = {
  user_id: 'user_lin_xia',
  tenant_id: 'tenant_muse_beauty',
  store_id: 'store_xintiandi',
  name: '林夏',
  role: 'manager',
  job_title: '新天地补鲜站店长',
  onboarding_date: '2026-04-01',
};

export const stores = [
  { store_id: 'store_xintiandi', name: '新天地补鲜站', city: '上海', completion_rate: 0.78, risk_signal_count: 5 },
  { store_id: 'store_xujiahui', name: '徐家汇补鲜站', city: '上海', completion_rate: 0.66, risk_signal_count: 8 },
  { store_id: 'store_hongqiao', name: '虹桥补鲜站', city: '上海', completion_rate: 0.84, risk_signal_count: 3 },
];

export const trainingSkills = [
  {
    skill_id: 'skill_store_profit_model',
    skill_name: '门店盈利模型总纲Skill',
    skill_type: 'framework',
    industry: 'beauty',
    target_roles: ['员工', '店长', '总部'],
    core_goal: '让培训服务于人头、到店率、月到店次数、单客年价值、房间产能和美容师产能。',
    scenario_tags: ['门店盈利模型', '顾客经营', '5A体验', '九大保障系统'],
    status: 'active',
    version_id: 'sv_store_profit_model_200',
    semver: '2.0.0',
    pass_rate: 0.81,
    source_documents: ['中妆单店盈利模型.pptx'],
    framework_layer: '门店盈利模型',
    execution_phase: '标准化前置认知',
    role_scope: ['employee', 'manager', 'hq'],
    ops_signal_mapping: ['到店率低', '复购下降', '房间产能低'],
    assessment_rubric: ['经营指标问答', '数据判断题', '角色化复盘'],
    evidence_requirement: ['知识测验', '门店数据复盘'],
  },
  {
    skill_id: 'skill_30day_store_landing',
    skill_name: '30天门店落地训练Skill',
    skill_type: 'landing',
    industry: 'beauty',
    target_roles: ['员工', '店长', '总部'],
    core_goal: '把先救命、再治病的30天计划拆成每日任务、训练、证据和验收。',
    scenario_tags: ['30天落地', '咨询诊断', '手法训练', '品项卡项', '验收'],
    status: 'active',
    version_id: 'sv_30day_store_landing_200',
    semver: '2.0.0',
    pass_rate: 0.76,
    source_documents: ['东方熏道项目计划书.docx'],
    framework_layer: '30天门店落地',
    execution_phase: '先救命',
    role_scope: ['employee', 'manager', 'hq'],
    ops_signal_mapping: ['新店执行弱', '流程漏项', '员工任务逾期'],
    assessment_rubric: ['每日打卡', '口试', '笔试', '现场演练', '总部抽检'],
    evidence_requirement: ['照片', '视频', '作业', '店长审核'],
  },
  {
    skill_id: 'skill_service_flow_6',
    skill_name: '六大服务流程标准化Skill',
    skill_type: 'sop',
    industry: 'beauty',
    target_roles: ['员工', '店长', '总部'],
    core_goal: '统一邀约、接待、参观、咨询、体验、售后的动作和表达。',
    scenario_tags: ['邀约', '接待', '参观', '咨询', '体验', '售后'],
    status: 'active',
    version_id: 'sv_service_flow_6_200',
    semver: '2.0.0',
    pass_rate: 0.83,
    source_documents: ['东方熏道项目计划书.docx', '中妆单店盈利模型.pptx'],
    framework_layer: '六大流程',
    execution_phase: '标准化',
    role_scope: ['employee', 'manager', 'hq'],
    ops_signal_mapping: ['售后未跟进', '体验后未转化', '低满意度'],
    assessment_rubric: ['流程演练', '话术陪练', '顾客视角检查'],
    evidence_requirement: ['流程打卡', '店长现场评分'],
  },
  {
    skill_id: 'skill_consult_diagnosis',
    skill_name: '咨询诊断与需求洞察Skill',
    skill_type: 'core_training',
    industry: 'beauty',
    target_roles: ['员工', '店长'],
    core_goal: '让员工从介绍产品转为先理解顾客需求、状态、顾虑和禁忌边界。',
    scenario_tags: ['需求提问', '症状确认', '体质判断', '项目匹配', '禁忌提醒'],
    status: 'active',
    version_id: 'sv_consult_diagnosis_200',
    semver: '2.0.0',
    pass_rate: 0.72,
    source_documents: ['东方熏道项目计划书.docx'],
    framework_layer: '咨询诊断',
    execution_phase: '先救命',
    role_scope: ['employee', 'manager'],
    ops_signal_mapping: ['需求记录缺失', '项目推荐失败', '投诉未听懂需求'],
    assessment_rubric: ['口试', 'AI顾客陪练', '风险话术检测'],
    evidence_requirement: ['顾客画像', '问诊记录', '店长审核'],
  },
  {
    skill_id: 'skill_project_hands',
    skill_name: '手法与项目专业通关Skill',
    skill_type: 'core_training',
    industry: 'beauty',
    target_roles: ['员工', '店长'],
    core_goal: '训练头、肩颈、背、腰臀、腿、腹、胸、淋巴等基础手法和项目表达。',
    scenario_tags: ['手法', '力度', '项目价值', '护理禁忌', '体验反馈'],
    status: 'installed',
    version_id: 'sv_project_hands_200',
    semver: '2.0.0',
    pass_rate: 0.69,
    source_documents: ['东方熏道项目计划书.docx'],
    framework_layer: '手法与项目专业',
    execution_phase: '先救命',
    role_scope: ['employee', 'manager'],
    ops_signal_mapping: ['服务评价低', '指定员工率低', '体验差'],
    assessment_rubric: ['现场手法', '视频证据', '店长评分'],
    evidence_requirement: ['手法视频', '店长验收', '总部抽检'],
  },
  {
    skill_id: 'skill_card_item_system',
    skill_name: '品项与卡项体系Skill',
    skill_type: 'conversion',
    industry: 'beauty',
    target_roles: ['员工', '店长', '总部'],
    core_goal: '把拓、留、升、转与顾客生命周期结合，训练员工讲清卡项价值而不是硬推销。',
    scenario_tags: ['拓留升转', '体验卡', '会员卡', '疗程价值', '价格异议'],
    status: 'active',
    version_id: 'sv_card_item_system_200',
    semver: '2.0.0',
    pass_rate: 0.74,
    source_documents: ['中妆单店盈利模型.pptx', '东方熏道项目计划书.docx'],
    framework_layer: '品项与卡项体系',
    execution_phase: '标准化',
    role_scope: ['employee', 'manager', 'hq'],
    ops_signal_mapping: ['新客未办卡', '疗程快用完', '复购低'],
    assessment_rubric: ['卡项匹配题', '价值表达陪练', '价格异议陪练'],
    evidence_requirement: ['话术录音', 'AI陪练评分', '店长复盘'],
  },
  {
    skill_id: 'skill_customer_361_profile',
    skill_name: '顾客经营361与B档案Skill',
    skill_type: 'ops_signal',
    industry: 'beauty',
    target_roles: ['员工', '店长', '总部'],
    core_goal: '把顾客偏好、需求、消费、满意度和到店计划沉淀成可训练、可复盘的经营动作。',
    scenario_tags: ['361顾客管理', 'B档案', '月度服务计划', '四次消费表'],
    status: 'active',
    version_id: 'sv_customer_361_profile_200',
    semver: '2.0.0',
    pass_rate: 0.67,
    source_documents: ['中妆单店盈利模型.pptx'],
    framework_layer: '顾客经营361',
    execution_phase: '精细化经营',
    role_scope: ['employee', 'manager', 'hq'],
    ops_signal_mapping: ['B档案缺失', '两个月不到店', '重复拒绝销售'],
    assessment_rubric: ['档案补全任务', '顾客分层判断', '邀约计划生成'],
    evidence_requirement: ['档案截图', '服务计划', '店长抽查'],
  },
  {
    skill_id: 'skill_5a_experience',
    skill_name: '5A体验与五感场景Skill',
    skill_type: 'experience',
    industry: 'beauty',
    target_roles: ['员工', '店长', '总部'],
    core_goal: '围绕好环境、好体验、好效果、好销售、好服务建立一致门店体验。',
    scenario_tags: ['好环境', '好体验', '好效果', '好销售', '好服务'],
    status: 'active',
    version_id: 'sv_5a_experience_200',
    semver: '2.0.0',
    pass_rate: 0.79,
    source_documents: ['中妆单店盈利模型.pptx', '东方熏道项目计划书.docx'],
    framework_layer: '5A体验',
    execution_phase: '标准化',
    role_scope: ['employee', 'manager', 'hq'],
    ops_signal_mapping: ['低满意度', '等待过久', '服务流程漏项'],
    assessment_rubric: ['场景照片', '顾客旅程检查', '服务陪练'],
    evidence_requirement: ['照片', '视频', '巡检记录'],
  },
  {
    skill_id: 'skill_manager_coach',
    skill_name: '店长带教与晨会复盘Skill',
    skill_type: 'manager',
    industry: 'beauty',
    target_roles: ['店长'],
    core_goal: '让店长按门店数据和员工短板生成晨会、补练、复盘和周报。',
    scenario_tags: ['晨会', '员工复盘', '补练', '门店周报'],
    status: 'active',
    version_id: 'sv_manager_coach_200',
    semver: '2.0.0',
    pass_rate: 0.86,
    source_documents: ['中妆单店盈利模型.pptx', '东方熏道项目计划书.docx'],
    framework_layer: '店长带教',
    execution_phase: '长期陪跑',
    role_scope: ['manager'],
    ops_signal_mapping: ['员工任务逾期', '到店率低', '投诉高'],
    assessment_rubric: ['晨会稿', '员工复盘卡', '本店训练周报'],
    evidence_requirement: ['晨会记录', '审核记录', '周报'],
  },
];

export const trainingTasks = [
  {
    task_id: 'task_001',
    title: '完成30天落地计划第8-14天咨询诊断预习',
    description: '按东方熏道计划进入咨询诊断阶段，先完成顾客沟通、症状确认、需求探索和禁忌边界知识卡。',
    task_type: 'knowledge',
    source_type: 'training_plan',
    source_skill_version_id: 'sv_30day_store_landing_200',
    source_agent_run_id: 'run_v3_plan_001',
    due_at: '今天 18:00',
    estimated_minutes: 15,
    priority: 'high',
    status: 'pending',
    completion_rule: '阅读4张知识卡并通过5题小测',
    score_required: 80,
  },
  {
    task_id: 'task_002',
    title: '六大服务流程AI顾客陪练',
    description: '围绕邀约、接待、参观、咨询、体验、售后做一轮完整演练，漏步骤自动扣分。',
    task_type: 'practice',
    source_type: 'training_plan',
    source_skill_version_id: 'sv_service_flow_6_200',
    source_agent_run_id: 'run_v3_plan_001',
    due_at: '今天 20:00',
    estimated_minutes: 18,
    priority: 'high',
    status: 'running',
    completion_rule: '完整流程评分达到85分',
    score_required: 85,
  },
  {
    task_id: 'task_003',
    title: '上传肩颈手法通关视频',
    description: '根据手法与项目专业通关Skill提交一段肩颈护理流程视频，由店长审核力度、节奏和禁忌提醒。',
    task_type: 'practice',
    source_type: 'training_plan',
    source_skill_version_id: 'sv_project_hands_200',
    source_agent_run_id: 'run_evidence_012',
    due_at: '明天 12:00',
    estimated_minutes: 12,
    priority: 'medium',
    status: 'pending',
    completion_rule: '上传视频并通过店长评分',
  },
  {
    task_id: 'task_004',
    title: '完成拓留升转卡项匹配题',
    description: '用顾客生命周期和部位痛点匹配体验卡、会员卡、疗程卡和转介绍方案。',
    task_type: 'knowledge',
    source_type: 'training_plan',
    source_skill_version_id: 'sv_card_item_system_200',
    source_agent_run_id: 'run_card_009',
    due_at: '今天 09:30',
    estimated_minutes: 10,
    priority: 'medium',
    status: 'completed',
    completion_rule: '完成10题匹配测验，正确率不低于80%',
    actual_score: 88,
  },
  {
    task_id: 'task_005',
    title: '新客体验后未办卡实战复盘',
    description: 'AI运营只读信号显示本周体验后未办卡提升18%，请完成体验转卡实战陪跑和风险话术检查。',
    task_type: 'real_action',
    source_type: 'ops_signal',
    source_skill_version_id: 'sv_card_item_system_200',
    source_agent_run_id: 'run_ops_signal_018',
    due_at: '今天 21:00',
    estimated_minutes: 12,
    priority: 'high',
    status: 'pending',
    completion_rule: '生成判断、跟进话术、禁用话术和补练建议',
  },
  {
    task_id: 'task_006',
    title: 'B档案缺失顾客补全训练',
    description: 'AI运营只读信号发现A类顾客偏好字段缺失，请训练员工用自然提问补齐顾客需求、偏好和预算信息。',
    task_type: 'real_action',
    source_type: 'ops_signal',
    source_skill_version_id: 'sv_customer_361_profile_200',
    source_agent_run_id: 'run_ops_signal_021',
    due_at: '明天 10:00',
    estimated_minutes: 14,
    priority: 'medium',
    status: 'pending',
    completion_rule: '完成顾客档案补全话术陪练并通过隐私边界检查',
  },
  {
    task_id: 'task_007',
    title: '店长生成明早10分钟晨会带教',
    description: '依据本店咨询诊断低分和体验转卡信号，生成晨会主题、示范话术和员工练习作业。',
    task_type: 'manager',
    source_type: 'ai_generated',
    source_skill_version_id: 'sv_manager_coach_200',
    source_agent_run_id: 'run_store_coach_006',
    due_at: '今天 22:00',
    estimated_minutes: 8,
    priority: 'high',
    status: 'pending',
    completion_rule: '确认晨会稿并分配给本店员工',
  },
  {
    task_id: 'task_008',
    title: '总部抽检5A体验证据',
    description: '总部抽检新天地补鲜站五感场景与5A体验证据，需店长补交护理间照片和售后回访记录。',
    task_type: 'group',
    source_type: 'ai_generated',
    source_skill_version_id: 'sv_5a_experience_200',
    source_agent_run_id: 'run_hq_audit_003',
    due_at: '昨天 18:00',
    estimated_minutes: 20,
    priority: 'high',
    status: 'overdue',
    completion_rule: '补齐照片、视频和售后记录后提交总部抽检',
  },
];

export const taskSummary = {
  today_task_count: trainingTasks.length,
  completed_count: trainingTasks.filter((task) => task.status === 'completed').length,
  overdue_count: trainingTasks.filter((task) => task.status === 'overdue').length,
  training_task_count: trainingTasks.filter((task) => task.task_type === 'knowledge').length,
  practice_task_count: trainingTasks.filter((task) => ['practice', 'makeup'].includes(task.task_type)).length,
  real_action_task_count: trainingTasks.filter((task) => task.task_type === 'real_action').length,
  ai_generated_count: trainingTasks.filter((task) => task.source_type === 'ai_generated').length,
};

export const managerCards = {
  store_completion_rate: 0.78,
  unfinished_user_count: 4,
  weak_scenarios: ['咨询诊断', '体验转卡', 'B档案补全'],
  pending_approval_count: 3,
  ai_recommendations: [
    '把30天落地第8-14天咨询诊断任务设为本周P0',
    '明早晨会围绕体验后未办卡做10分钟示范',
    '将AI运营B档案缺失信号转为员工实战补练',
  ],
};

export const agentRuns = [
  {
    run_id: 'run_v3_plan_001',
    agent_type: 'TrainingPlannerAgent',
    trigger_type: 'natural_language',
    status: 'running',
    progress_percent: 72,
    current_message: '正在按角色、30天计划和门店弱项生成实战训练任务',
    source_skill_version_id: 'sv_30day_store_landing_200',
    linked_object_type: 'practice_field_plan',
    linked_object_id: 'plan_practice_field_001',
    started_at: '2026-04-27T08:12:00+08:00',
  },
  {
    run_id: 'run_ops_signal_018',
    agent_type: 'OpsSignalTrainingAgent',
    trigger_type: 'ops_signal',
    status: 'waiting_approval',
    progress_percent: 88,
    current_message: '已将体验后未办卡信号转为实战陪跑任务，等待店长确认',
    source_skill_version_id: 'sv_card_item_system_200',
    linked_object_type: 'training_task',
    linked_object_id: 'task_005',
    started_at: '2026-04-27T08:22:00+08:00',
  },
];

export const abilityProfile = {
  user_id: 'user_chen_yu',
  name: '陈雨',
  role_scope: '员工视图',
  ability: {
    门店盈利理解: 82,
    六大服务流程: 86,
    咨询诊断: 74,
    手法与项目: 69,
    品项卡项表达: 76,
    顾客经营361: 66,
    风险边界: 92,
  },
  gaps: [
    {
      scenario: '手法与项目',
      score: 69,
      reason: '动作顺序能完成，但力度说明和禁忌提醒不稳定。',
      recommended_action: '上传肩颈手法视频并完成店长复评。',
    },
    {
      scenario: '顾客经营361',
      score: 66,
      reason: '能记录基础信息，但偏好、预算和到店计划缺失。',
      recommended_action: '完成B档案补全实战陪跑。',
    },
  ],
  last_practice_at: '今天 10:42',
};

export const practiceScenarios = [
  {
    scenario_id: 'scenario_profit_model',
    scenario_name: '门店盈利模型总纲',
    scenario_type: 'core',
    difficulty_level: 'P0',
    customer_profile: { state: '用人头、到店率、月到店次数和单客年价值解释训练目标' },
    must_cover_points: ['人头', '到店率', '单客年价值'],
    forbidden_phrases: ['只把培训当作知识学习'],
    score: 82,
  },
  {
    scenario_id: 'scenario_30day_landing',
    scenario_name: '30天门店落地计划',
    scenario_type: 'core',
    difficulty_level: 'P0',
    customer_profile: { state: '先救命、再治病，拆解每日任务、训练、证据和验收' },
    must_cover_points: ['咨询诊断', '手法训练', '品项卡项', '验收'],
    forbidden_phrases: ['跳过基础流程直接做销售训练'],
    score: 76,
  },
  {
    scenario_id: 'scenario_service_flow_6',
    scenario_name: '六大服务流程演练',
    scenario_type: 'core',
    difficulty_level: 'P0',
    customer_profile: { state: '从邀约到售后完整演练，任何漏项都进入补练' },
    must_cover_points: ['邀约', '接待', '参观', '咨询', '体验', '售后'],
    forbidden_phrases: ['一上来推卡', '不做售后确认'],
    score: 86,
  },
  {
    scenario_id: 'scenario_consult_diagnosis',
    scenario_name: '咨询诊断与需求洞察',
    scenario_type: 'core',
    difficulty_level: 'P0',
    customer_profile: { state: '顾客想改善但表达模糊，需要先问需求和顾虑' },
    must_cover_points: ['开放式提问', '症状确认', '体质/项目匹配', '禁忌提醒'],
    forbidden_phrases: ['直接推荐最贵项目', '制造焦虑'],
    score: 74,
  },
  {
    scenario_id: 'scenario_no_card_after_trial',
    scenario_name: '新客体验后未办卡',
    scenario_type: 'field',
    difficulty_level: 'AI运营信号',
    customer_profile: { state: '体验后满意但不办卡，可能是价值感、预算或信任问题' },
    must_cover_points: ['确认体验', '价值复盘', '轻选择', '风险边界'],
    forbidden_phrases: ['限时压迫', '承诺一次见效'],
    score: 71,
  },
  {
    scenario_id: 'scenario_old_customer_silent',
    scenario_name: '老客30/60天未到店',
    scenario_type: 'field',
    difficulty_level: 'AI运营信号',
    customer_profile: { state: '老客沉默，需要关怀开场、轻预约和到店计划' },
    must_cover_points: ['关怀', '复查', '轻预约'],
    forbidden_phrases: ['高频催促', '制造皮肤焦虑'],
    score: 68,
  },
  {
    scenario_id: 'scenario_b_profile_missing',
    scenario_name: 'B档案缺失补全',
    scenario_type: 'field',
    difficulty_level: 'AI运营信号',
    customer_profile: { state: '顾客偏好、预算和到店计划不完整，需要自然补问' },
    must_cover_points: ['偏好', '需求', '预算', '隐私边界'],
    forbidden_phrases: ['越界询问隐私', '未经授权外发资料'],
    score: 66,
  },
  {
    scenario_id: 'scenario_manager_morning',
    scenario_name: '店长晨会复盘',
    scenario_type: 'review',
    difficulty_level: '店长',
    customer_profile: { state: '依据本店弱项生成10分钟晨会稿、示范话术和作业' },
    must_cover_points: ['弱项', '示范', '作业', '审核'],
    forbidden_phrases: ['公开羞辱员工', '未经审批公开排名'],
    score: 78,
  },
  {
    scenario_id: 'scenario_hq_audit',
    scenario_name: '总部抽检与SOP沉淀',
    scenario_type: 'review',
    difficulty_level: '总部',
    customer_profile: { state: '按Skill版本、证据和指标抽检门店训练落地' },
    must_cover_points: ['Skill版本', '证据', '指标', '回滚'],
    forbidden_phrases: ['无证据发布标杆', '绕过权限跨店查看'],
    score: 84,
  },
];

export const practiceHistory = [
  { session_id: 'ps_201', scenario: '咨询诊断与需求洞察', score: 74, passed: false, finished_at: '今天 10:42' },
  { session_id: 'ps_200', scenario: '六大服务流程演练', score: 86, passed: true, finished_at: '昨天 17:20' },
  { session_id: 'ps_199', scenario: '风险边界与异常升级', score: 92, passed: true, finished_at: '昨天 09:16' },
];

export const fieldGuidanceSamples = [
  {
    guidance_id: 'fg_101',
    scenario_text: 'AI运营显示新客体验后未办卡增加，员工不知道怎么跟进。',
    judgment: '这是体验转卡实战，不是直接追单。需要先复盘体验感受，再判断顾客是预算、信任、周期还是价值感不足。',
    suggested_script: '今天先不急着让顾客做重决定，可以先确认她对这次护理的真实感受，再给一个低压力的下次复查或轻量方案。',
    risks: ['不制造焦虑', '不承诺一次见效', '不直接由培训系统触达顾客'],
    next_actions: ['生成体验转卡补练', '保存复盘', '如需客户触达则转AI运营请求'],
    handoff_available: true,
  },
  {
    guidance_id: 'fg_102',
    scenario_text: '顾客护理后脸红，说是不是过敏。',
    judgment: '涉及皮肤异常，必须先安抚、记录并升级，不做医学判断。',
    suggested_script: '先别担心，我先帮您记录现在的情况和持续时间。我们暂停继续推荐项目，我请店长一起确认后续处理。',
    risks: ['不能说肯定没事', '不能做医学诊断', '不能承诺马上恢复'],
    next_actions: ['记录症状和时间', '转店长/专业咨询', '加入风险话术复训'],
    handoff_available: false,
  },
  {
    guidance_id: 'fg_103',
    scenario_text: 'AI运营发现B档案里顾客偏好和预算字段缺失。',
    judgment: '这是顾客经营361训练，应训练员工在服务沟通中自然补齐，而不是机械追问。',
    suggested_script: '为了后面护理更贴合您的习惯，我确认两个小点：您更在意护理时的力度、安静程度，还是后续效果的持续感？',
    risks: ['不越界询问隐私', '不外发顾客资料', '只读取训练相关脱敏信号'],
    next_actions: ['生成B档案补全陪练', '店长抽查记录', '同步本店周报'],
    handoff_available: true,
  },
];

export const approvals = [
  {
    approval_id: 'approval_001',
    approval_type: 'publish_practice_field_plan',
    risk_level: 'medium',
    status: 'pending',
    title: '发布30天门店落地训练到新天地补鲜站',
    impact_scope: '5名员工，18个核心训练与实战陪跑任务',
    recommended_decision: '建议通过，计划只包含训练、作业和店长审核动作。',
    source_agent_run_id: 'run_v3_plan_001',
    source_skill_version_id: 'sv_30day_store_landing_200',
  },
  {
    approval_id: 'approval_002',
    approval_type: 'ops_handoff_request',
    risk_level: 'high',
    status: 'pending',
    title: '将体验后未办卡话术转AI运营触达请求',
    impact_scope: '仅生成交接请求，不由AI培训系统直接触达顾客',
    recommended_decision: '建议转AI运营审批执行，AI培训只保留训练建议和话术边界。',
    source_agent_run_id: 'run_ops_signal_018',
    source_skill_version_id: 'sv_card_item_system_200',
  },
];

export const chatMessages = [
  {
    message_id: 'msg_001',
    role: 'user',
    content: '按AI运营信号给本店生成本周实战训练',
    created_at: '08:12',
  },
  {
    message_id: 'msg_002',
    role: 'assistant',
    content: '已读取角色权限、V3 Skill目录和AI运营只读信号，生成核心训练、实战陪跑和补练复盘。',
    created_at: '08:13',
    cards: [
      {
        card_id: 'card_practice_field_001',
        card_type: 'core_training_path',
        title: '本周实战训练路径',
        payload: {
          modules: ['咨询诊断', '六大服务流程', '体验转卡', 'B档案补全'],
          tasks: 8,
          pass_rule: '核心场景达到80分，实战场景需店长确认',
        },
        actions: [{ label: '去实战', action: 'open_practice' }, { label: '提交审批', action: 'create_approval' }],
      },
      {
        card_id: 'card_ops_signal_001',
        card_type: 'ops_signal_training',
        title: 'AI运营信号已转训练',
        payload: {
          signals: ['新客体验后未办卡', 'B档案缺失', '老客30天未到店'],
          read_only: true,
        },
        actions: [{ label: '查看任务', action: 'open_tasks' }],
      },
    ],
  },
];

export const storePulse = {
  store_id: 'store_xintiandi',
  store_name: '新天地补鲜站',
  signals: [
    { label: '体验后未办卡', value: '+18%', tone: 'warning' },
    { label: 'B档案缺失', value: '23条', tone: 'danger' },
    { label: '核心训练完成率', value: '78%', tone: 'success' },
  ],
  recommendation: '建议将体验转卡、咨询诊断和B档案补全设为本周实战训练重点，所有客户触达动作转AI运营审批执行。',
};

export const roleWorkspace = {
  current_role: 'manager',
  identities: [
    {
      key: 'employee',
      label: '员工',
      owner: '陈雨',
      scope: '个人任务与个人训练',
      headline: '完成我的核心训练和实战补练',
      stats: [
        { label: '今日任务', value: '4' },
        { label: '待补练', value: '2' },
        { label: '通关率', value: '74%' },
      ],
      visible: ['我的任务', '我的实战', '能力画像', '个人AI培训'],
      ai_commands: ['问知识', '练话术', '请求实战陪跑', '查看个人反馈'],
      blocked: ['跨员工数据', '发布门店任务', '修改总部Skill'],
      responsibilities: ['学习', '陪练', '上传证据', '完成补练'],
    },
    {
      key: 'manager',
      label: '店长',
      owner: '林夏',
      scope: '新天地补鲜站',
      headline: '管理本店员工、审核作业和生成晨会带教',
      stats: [
        { label: '本店员工', value: '18' },
        { label: '待审核', value: '6' },
        { label: '完成率', value: '78%' },
      ],
      visible: ['本店任务', '员工弱项', '作业审核', '门店周报'],
      ai_commands: ['生成门店训练计划', '员工复盘', '晨会稿', '本店周报'],
      blocked: ['无授权门店数据', '修改总部标准', '绕过AI运营触达客户'],
      responsibilities: ['分配任务', '审核证据', '晨会带教', '门店复盘'],
    },
    {
      key: 'hq',
      label: '总部',
      owner: '培训总部',
      scope: '授权门店与企业Skill',
      headline: '发布标准、配置权限、抽检多店训练效果',
      stats: [
        { label: '门店', value: '3' },
        { label: 'Skill版本', value: '9' },
        { label: '抽检项', value: '12' },
      ],
      visible: ['多店看板', 'Skill中心', 'SOP建模', '权限矩阵'],
      ai_commands: ['发布Skill', 'SOP建模', '多店分析', '总部抽检计划'],
      blocked: ['替员工完成训练', '绕过店长审核', '直接执行客户动作'],
      responsibilities: ['发布标准', '定义权限', '跨店复盘', '总部抽检'],
    },
  ],
  permission_matrix: [
    { dimension: '页面可见', employee: '个人任务/个人实战', manager: '本店任务/员工/报告', hq: '多店/Skill/SOP/权限' },
    { dimension: '数据范围', employee: '自己', manager: '本店', hq: '授权门店/企业汇总' },
    { dimension: 'AI指令', employee: '个人学习与实战陪跑', manager: '门店计划与员工复盘', hq: 'Skill发布与多店分析' },
    { dimension: '任务创建', employee: '个人自建或请求', manager: '本店任务', hq: '企业模板任务' },
    { dimension: '审核责任', employee: '提交证据', manager: '审核员工证据', hq: '抽检门店和Skill效果' },
    { dimension: 'AI运营信号', employee: '个人脱敏信号', manager: '本店训练相关信号', hq: '授权门店汇总信号' },
  ],
  approvals: [
    { title: '陈雨肩颈手法视频待审核', role: '店长', status: '待审核' },
    { title: '总部抽检5A体验证据', role: '总部', status: '需补交' },
    { title: '体验后未办卡转AI运营请求', role: '店长', status: '待确认' },
  ],
};

export const roleDashboardData = {
  employee: {
    key: 'employee',
    label: '员工',
    accountRole: '员工账号',
    owner: '陈雨',
    title: '新天地补鲜站美容师',
    scope: '个人培训与个人实战',
    color: '#0ea5e9',
    visibleFor: ['employee', 'manager'],
    identitySummary: '员工视图聚焦个人培训任务、核心能力通关和真实业务中的实战提升。',
    currentStage: {
      title: '30天门店落地 第8-14天',
      subtitle: '咨询诊断、六大服务流程、B档案补全',
      progress: 62,
      next: '第15-21天进入手法与项目专业通关',
    },
    trainingGoal: '完成公司标准培训，掌握门店盈利模型下的服务、咨询、转化与顾客经营基础。',
    progressStats: [
      { label: '计划进度', value: '62%', tone: 'blue' },
      { label: '核心通关', value: '74%', tone: 'green' },
      { label: '待补练', value: '2', tone: 'orange' },
      { label: '风险红线', value: '0', tone: 'slate' },
    ],
    planOverview: [
      { title: '公司30天落地计划', desc: '当前进入咨询诊断与服务流程标准化阶段。', status: '进行中' },
      { title: '门店盈利模型认知', desc: '用人头、到店率、单客年价值理解培训目标。', status: '已通关' },
      { title: '实战陪跑计划', desc: '根据AI运营只读信号补练体验转卡和B档案补全。', status: '待加强' },
    ],
    gapsTitle: '个人能力短板',
    gaps: [
      { title: '手法与项目', value: '69分', desc: '动作顺序能完成，但力度说明和禁忌提醒不稳定。' },
      { title: '顾客经营361', value: '66分', desc: '偏好、预算和到店计划记录不完整。' },
      { title: '咨询诊断', value: '74分', desc: '能问基础需求，但顾虑确认和项目匹配仍需补练。' },
    ],
    focusPoints: [
      { title: '完成咨询诊断预习', desc: '先补齐顾客需求、症状确认和禁忌边界知识。', href: '/tasks', action: '去任务' },
      { title: '进入体验转卡实战', desc: '用AI顾客陪练处理体验满意但不办卡的情况。', href: '/practice', action: '去实战' },
      { title: '补交肩颈手法视频', desc: '提交证据后由店长审核力度、节奏和风险提醒。', href: '/tasks', action: '去任务' },
    ],
    aiSuggestions: [
      '帮我练一轮咨询诊断顾客问答',
      '根据我的短板生成今天的补练顺序',
      '模拟体验后不办卡顾客，我来回答',
    ],
    permissionSummary: [
      '可查看个人任务、个人实战和个人训练报告',
      '可使用AI进行知识问答、话术陪练和个人复盘',
      '不可查看其他员工明细、发布门店任务或触发AI运营客户动作',
    ],
  },
  manager: {
    key: 'manager',
    label: '店长',
    accountRole: '店长账号',
    owner: '林夏',
    title: '新天地补鲜站店长',
    scope: '本店培训与员工管理',
    color: '#10b981',
    visibleFor: ['manager'],
    identitySummary: '店长视图聚焦本人店铺管理训练、本店员工培训进度和证据审核责任。',
    currentStage: {
      title: '店长带教与门店SOP落地',
      subtitle: '晨会带教、员工复盘、门店弱项补练',
      progress: 78,
      next: '进入本店周报复盘和总部抽检准备',
    },
    trainingGoal: '完成店长管理训练，并把员工培训、实战补练和门店经营弱项转化为可执行的带教动作。',
    progressStats: [
      { label: '店长计划', value: '78%', tone: 'green' },
      { label: '员工完成率', value: '72%', tone: 'blue' },
      { label: '待审核', value: '6', tone: 'orange' },
      { label: '弱项场景', value: '3', tone: 'red' },
    ],
    planOverview: [
      { title: '店长培训计划', desc: '围绕晨会、带教、员工复盘和门店周报完成管理训练。', status: '进行中' },
      { title: '本店员工训练计划', desc: '新天地补鲜站员工正在执行30天落地第8-14天任务。', status: '需跟进' },
      { title: '门店实战陪跑', desc: '体验转卡、B档案补全、咨询诊断是本周重点。', status: '重点' },
    ],
    staffTrainingSummary: [
      { label: '员工训练完成率', value: '72%', desc: '18名员工中4人低于本周进度。' },
      { label: '证据待审核', value: '6条', desc: '主要集中在肩颈手法视频和5A体验照片。' },
      { label: '共性短板', value: '3项', desc: '咨询诊断、体验转卡、B档案补全。' },
    ],
    gapsTitle: '管理与带教短板',
    gaps: [
      { title: '晨会带教', value: '待加强', desc: '需要把门店弱项拆成10分钟示范和员工练习。' },
      { title: '证据审核', value: '6条', desc: '手法视频和5A体验证据需要今天完成审核。' },
      { title: '员工补练', value: '4人', desc: '低于进度员工需要安排补练和复盘。' },
    ],
    focusPoints: [
      { title: '审核员工手法视频', desc: '优先处理肩颈手法通关证据，避免阻塞员工进度。', href: '/tasks', action: '去任务' },
      { title: '生成明早晨会带教', desc: '围绕体验转卡和B档案补全生成示范话术。', href: '/ai', action: '问AI' },
      { title: '查看员工实战短板', desc: '按AI运营信号安排本店实战补练。', href: '/practice', action: '去实战' },
    ],
    aiSuggestions: [
      '按本店弱项生成明早10分钟晨会稿',
      '把未完成员工分成补练名单和跟进建议',
      '根据体验未办卡信号生成店长复盘提纲',
    ],
    permissionSummary: [
      '可查看本店员工训练进度、弱项和证据审核状态',
      '可生成本店任务、晨会带教、员工复盘和门店日报',
      '不可查看未授权门店数据、修改总部Skill或直接触达客户',
    ],
  },
  hq: {
    key: 'hq',
    label: '总部',
    accountRole: '总部账号',
    owner: '培训总部',
    title: '培训运营负责人',
    scope: '企业培训计划与进度治理',
    color: '#8b5cf6',
    visibleFor: ['hq'],
    identitySummary: '总部视图聚焦培训发布、跨店进度、Skill/SOP覆盖和抽检治理。',
    currentStage: {
      title: 'V3培训计划执行监控',
      subtitle: '30天落地、门店盈利模型、店长带教体系',
      progress: 69,
      next: '发布下一轮Skill灰度版本并抽检低完成门店',
    },
    trainingGoal: '制定和发布培训计划，管理员工与店长完成情况，持续优化Skill、SOP和门店落地质量。',
    progressStats: [
      { label: '计划执行', value: '69%', tone: 'blue' },
      { label: '门店覆盖', value: '3家', tone: 'green' },
      { label: '风险门店', value: '1', tone: 'red' },
      { label: 'Skill版本', value: '9', tone: 'purple' },
    ],
    planOverview: [
      { title: '30天门店落地计划', desc: '三家门店进入咨询诊断与服务流程标准化阶段。', status: '执行中' },
      { title: '店长带教训练', desc: '店长需完成晨会、员工复盘和本店周报训练。', status: '跟进中' },
      { title: 'Skill/SOP覆盖', desc: '门店盈利模型、六大流程、361顾客经营已覆盖。', status: '已发布' },
    ],
    roleCompletionSummary: [
      { label: '员工完成率', value: '71%', desc: '咨询诊断和B档案补全拖慢整体进度。' },
      { label: '店长完成率', value: '82%', desc: '晨会带教已覆盖，证据审核速度仍需提升。' },
      { label: '总部抽检通过', value: '76%', desc: '5A体验证据质量差异较大。' },
    ],
    storeTrainingSummary: [
      { store: '新天地补鲜站', progress: '78%', risk: '体验转卡' },
      { store: '徐家汇补鲜站', progress: '66%', risk: 'B档案缺失' },
      { store: '虹桥补鲜站', progress: '84%', risk: '证据补交' },
    ],
    gapsTitle: '计划执行风险',
    gaps: [
      { title: '徐家汇补鲜站进度偏低', value: '66%', desc: '员工B档案补全和咨询诊断任务滞后。' },
      { title: '5A体验证据不齐', value: '12项', desc: '总部抽检需要明确照片、视频和售后记录标准。' },
      { title: 'Skill版本反馈', value: '待汇总', desc: '需要从门店复盘中沉淀下一版训练内容。' },
    ],
    focusPoints: [
      { title: '查看门店进度风险', desc: '优先关注低完成率和高补练门店。', href: '/tasks', action: '看进度' },
      { title: '生成总部抽检计划', desc: '按Skill版本、证据质量和指标波动生成抽检安排。', href: '/ai', action: '问AI' },
      { title: '更新Skill中心内容', desc: '把本轮门店共性问题沉淀为下一版TrainingSkill。', href: '/me?tab=skill', action: '去设置' },
    ],
    aiSuggestions: [
      '按三家门店完成率生成总部培训周报',
      '根据低完成门店生成抽检计划',
      '汇总员工和店长短板，形成下一版Skill更新建议',
    ],
    permissionSummary: [
      '可查看授权门店汇总进度、Skill/SOP覆盖和总部抽检结果',
      '可发布企业TrainingSkill、培训SOP和跨店模板任务',
      '不可代替员工/店长完成训练，客户触达仍必须转AI运营系统',
    ],
  },
};

export const phasePlan = [
  { phase: 'Phase 1', title: 'V3导航与实战合并', scope: '任务、实战、AI培训、角色、我的', priority: 'P0' },
  { phase: 'Phase 2', title: '核心训练与实战陪跑', scope: '门店盈利模型、30天落地、AI运营只读信号', priority: 'P0' },
  { phase: 'Phase 3', title: '角色培训工作台', scope: '员工、店长、总部培训视图与权限摘要', priority: 'P0' },
  { phase: 'Phase 4', title: 'Skill与SOP生态', scope: 'Skill发布、SOP建模、总部抽检', priority: 'P1' },
];

export function getTaskPageDTO() {
  return {
    summary: taskSummary,
    running_runs: agentRuns,
    tasks: trainingTasks,
    manager_cards: managerCards,
  };
}

export function getPracticeOverviewDTO() {
  return {
    training_map: {
      title: '门店盈利模型到30天落地',
      progress: 0.62,
      modules: ['门店盈利模型', '30天落地', '六大服务流程', '咨询诊断', '手法项目', '品项卡项', '361顾客经营', '5A体验'],
    },
    role_progress: {
      role: '店长视图',
      core_pass_rate: 0.78,
      field_case_count: 7,
      evidence_pending: 6,
    },
    ability_profile: abilityProfile,
    today_practice: trainingTasks.filter((task) => ['practice', 'makeup', 'real_action'].includes(task.task_type)),
    scenarios: practiceScenarios,
    history: practiceHistory,
    store_pulse: storePulse,
  };
}

export function createFieldGuidance(input = {}) {
  const text = input.scenario_text || '';
  let matched = fieldGuidanceSamples[0];

  if (text.includes('脸红') || text.includes('过敏') || text.includes('投诉')) {
    matched = fieldGuidanceSamples[1];
  } else if (text.includes('档案') || text.includes('B档案') || text.includes('偏好')) {
    matched = fieldGuidanceSamples[2];
  }

  return {
    ...matched,
    guidance_id: `fg_${Date.now()}`,
    scenario_text: text || matched.scenario_text,
  };
}
