services:
  ai-train:
    container_name: ai-train-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    extra_hosts:
      - "host.docker.internal:host-gateway"
